baseURL = "https://purpleidea.com/"
languageCode = "en-ca"
title = "purpleidea.com"

pygmentsCodeFences = true

[author]
  name = "James Shubin"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  github = "https://github.com/purpleidea/"
  twitter = "https://twitter.com/purpleidea"
  publickeyfile = "static/james@shubin.ca.asc"

  # https://api.staticman.net/v2/entry/{GITHUB USERNAME}/{GITHUB REPOSITORY}/{BRANCH}/{PROPERTY (optional)}
  staticmanURL = "https://api.staticman.net/v2/entry/purpleidea/purpleidea.com/master"
  staticmanPR = "https://github.com/purpleidea/purpleidea.com/pulls"
  # The spam bots have become way too proficient. Hopefully this will stop them.
  # The secret from google needs to be encrypted. Use this special endpoint
  # https://api.staticman.net/v2/encrypt/YOUR-SECRET to encrypt the secret.
  staticmanCaptchaSiteKey = "6Lc0u2EUAAAAAImKX7XafINIzeoLZFQCGFKF7qCp"
  staticmanCaptchaSecret = "AEl4ul2uMOx2EL2LMm/84zzh8mWLYIYW+v2EEu7webGOtAqyQiLBa6QLjPgnlyNjJxE3UeccxuBQIWqPzG96FsVl0AVTihhHt3OGR1hteAZUAhoJjnH+7PoyC3x7d4KDLypopDn+HzWowOpAZuvfHE08n+G4omrP5fUfkOrH03A="
